#!/usr/bin/env python3
"""
Budget Enduro site builder.

Header, footer and nav live here once. Run `python3 build.py` and every
page in site/ is regenerated. Edit this file, not the HTML.
"""
import os, re, hashlib

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'site')


def _asset_ver():
    """Content hash of the client JS, so a deploy busts the browser cache."""
    h = hashlib.md5()
    base = os.path.dirname(os.path.abspath(__file__))
    for fn in ('assets/be.js', 'assets/venues.js'):
        try:
            with open(os.path.join(base, fn), 'rb') as f:
                h.update(f.read())
        except OSError:
            pass
    return h.hexdigest()[:8]


ASSET_VER = _asset_ver()

NAV = [
    ('index.html',        'Home'),
    ('events.html',       'Events'),
    ('how-it-works.html', 'How it works'),
    ('rules.html',        'Rules'),
    ('results.html',      'Results'),
    ('gallery.html',      'Gallery'),
    ('faq.html',          'FAQ'),
    ('contact.html',      'Contact'),
]


# ============================================================ VENUES
# Single source of truth for circuits. Feeds:
#   - assets/venues.js  (runtime: event cards, entry page)
#   - the minimum lap table on rules.html
#   - the circuit table on events.html
# Mirror these fields as a `venues` table in Supabase so ArgusIQ event
# setup can hydrate an event the moment a track is selected.
VENUES = [
    dict(slug='calder-park', name='Calder Park Raceway', short='Calder Park', state='VIC',
         address='377 Calder Fwy, Calder Park, Victoria',
         lat=-37.6497, lng=144.7594,
         min_lap=74, length_km=2.30, turns=10, direction='Clockwise',
         pit_speed=60, map='/assets/tracks/calder-park.svg'),
    dict(slug='sandown', name='Sandown Raceway', short='Sandown', state='VIC',
         address='591-659 Princes Hwy, Springvale, Victoria',
         lat=-37.9469, lng=145.1653,
         min_lap=95, length_km=3.10, turns=13, direction='Clockwise',
         pit_speed=60, map='/assets/tracks/sandown.svg'),
    dict(slug='mallala', name='Mallala Motorsport Park', short='Mallala', state='SA',
         address='Aerodrome Rd, Mallala, South Australia',
         lat=-34.4361, lng=138.5122,
         min_lap=87, length_km=2.56, turns=10, direction='Clockwise',
         pit_speed=40, map='/assets/tracks/mallala.svg'),
]

VENUE = {v['slug']: v for v in VENUES}


def min_lap_text(v):
    return '%d sec' % v['min_lap'] if v['min_lap'] else 'To be advised'


def emit_venues_js():
    """One source of truth -> a runtime module the pages read."""
    import json
    rows = ',\n'.join('  ' + json.dumps(v) for v in VENUES)
    js = ('/* GENERATED BY build.py - do not edit by hand. */\n'
          'var VENUES = [\n' + rows + '\n];\n'
          'var VENUE = {};\n'
          'VENUES.forEach(function(v){ VENUE[v.slug] = v; });\n')
    path = os.path.join(OUT, 'assets', 'venues.js')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(js)
    print('  assets/venues.js       %7s bytes' % format(len(js), ','))


def min_lap_table():
    rows = '\n'.join(
        '          <tr><td>%s</td><td>%s</td></tr>' % (v['name'], min_lap_text(v))
        for v in VENUES)
    return ('<div class="scroller"><table>\n'
            '        <thead><tr><th>Circuit</th><th>Minimum lap time</th></tr></thead>\n'
            '        <tbody>\n' + rows + '\n'
            '        </tbody>\n      </table></div>')


def circuit_table():
    rows = '\n'.join(
        '          <tr><td>%s</td><td>%s</td><td>%.2f km</td><td>%d</td><td>%s</td></tr>'
        % (v['name'], v['state'], v['length_km'], v['turns'], min_lap_text(v))
        for v in VENUES)
    return ('<div class="scroller"><table>\n'
            '        <thead><tr><th>Circuit</th><th>State</th><th>Length</th>'
            '<th>Turns</th><th>Minimum lap</th></tr></thead>\n'
            '        <tbody>\n' + rows + '\n'
            '        </tbody>\n      </table></div>')


ARROW = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" '
         'aria-hidden="true"><path d="M4 12h15M13 6l6 6-6 6"/></svg>')


def head(title, desc, page):
    return f'''<!DOCTYPE html>
<html lang="en-AU">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#080A0B">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="/assets/og.jpg">
<meta property="og:type" content="website">
<link rel="icon" href="/assets/favicon.png">
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,600;0,700;0,800;1,700;1,800&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/be.css">
</head>
<body>
'''


def link(href):
    """cleanUrls is on in vercel.json, so links drop the .html"""
    if href == 'index.html':
        return '/'
    return href[:-5] if href.endswith('.html') else href


def header(page):
    links = ''.join(
        f'      <a href="{link(href)}"{" class=\"is-active\"" if href == page else ""}>{label}</a>\n'
        for href, label in NAV)
    return f'''<header class="site-header">
  <div class="container header-inner">
    <a class="brand" href="/" aria-label="Budget Enduro home">
      <img src="/assets/be-logo.png" alt="Budget Enduro" width="900" height="286">
    </a>
    <button class="nav-toggle" id="navToggle" aria-expanded="false" aria-controls="siteNav">Menu</button>
    <nav class="site-nav" id="siteNav" aria-label="Main">
{links}      <a class="btn btn-primary btn-sm" href="enter">Enter an event {ARROW}</a>
    </nav>
  </div>
</header>
'''


def page_head(crumb, title, blurb=''):
    b = f'\n    <p>{blurb}</p>' if blurb else ''
    return f'''<div class="page-head">
  <div class="container">
    <p class="crumb">{crumb}</p>
    <h1>{title}</h1>{b}
  </div>
</div>
'''


CTA_BAND = f'''<section class="cta-band">
  <div class="container cta-band-inner">
    <h2>Grab your mates. Find a car. Go racing.</h2>
    <a class="btn" href="enter">Enter an event {ARROW}</a>
  </div>
</section>
'''

FOOTER = f'''<div class="chequer" aria-hidden="true"></div>
<footer class="site-footer">
  <div class="container">
    <div class="foot-grid">
      <div>
        <img class="flogo" src="/assets/be-logo.png" alt="Budget Enduro" width="900" height="286">
        <p class="foot-tag">Real cars. Real people. Real racing.</p>
        <div class="socials">
          <a href="#" aria-label="Budget Enduro on Facebook"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M13.5 21v-8h2.7l.4-3.1h-3.1V7.9c0-.9.25-1.5 1.55-1.5h1.65V3.6c-.29-.04-1.27-.12-2.4-.12-2.38 0-4 1.45-4 4.11V9.9H7.6V13h2.7v8h3.2z"/></svg></a>
          <a href="#" aria-label="Budget Enduro on Instagram"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="4.5"/><circle cx="12" cy="12" r="4"/><circle cx="17.2" cy="6.8" r="1.1" fill="currentColor" stroke="none"/></svg></a>
          <a href="#" aria-label="Budget Enduro on YouTube"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M22 12s0-3.2-.4-4.7a2.5 2.5 0 00-1.7-1.8C18.3 5 12 5 12 5s-6.3 0-7.9.5A2.5 2.5 0 002.4 7.3C2 8.8 2 12 2 12s0 3.2.4 4.7c.2.9.9 1.6 1.7 1.8 1.6.5 7.9.5 7.9.5s6.3 0 7.9-.5a2.5 2.5 0 001.7-1.8c.4-1.5.4-4.7.4-4.7zM10 15.2V8.8l5.2 3.2-5.2 3.2z"/></svg></a>
        </div>
      </div>
      <div>
        <h4>Quick links</h4>
        <ul>
          <li><a href="how-it-works">How it works</a></li>
          <li><a href="events">Events</a></li>
          <li><a href="rules">Rules</a></li>
          <li><a href="results">Results</a></li>
          <li><a href="faq">FAQ</a></li>
          <li><a href="https://timing.argusiq.io">Live timing</a></li>
        </ul>
      </div>
      <div>
        <h4>Circuits</h4>
        <ul>
          <li>Calder Park, VIC</li>
          <li>Sandown Raceway, VIC</li>
          <li>Broadford, VIC</li>
          <li>Mallala Motorsport Park, SA</li>
          <li>Carnell Raceway, QLD</li>
        </ul>
      </div>
      <div>
        <h4>Contact us</h4>
        <ul>
          <li><a href="mailto:race@budgetenduro.com.au">race@budgetenduro.com.au</a></li>
          <li><a href="tel:+61357626000">03 5762 6000</a></li>
        </ul>
        <a class="btn btn-primary btn-sm" style="margin-top:16px" href="enter">Enter an event {ARROW}</a>
      </div>
    </div>
    <div class="colophon">
      <span>&copy; 2026 Budget Enduro &middot; Tampered Motorsport. All rights reserved.</span>
      <span>Entries, payments and timing by <a href="https://www.argusiq.io">ArgusIQ</a></span>
    </div>
  </div>
</footer>

<div class="sticky-cta">
  <a class="btn btn-primary" href="enter">Enter an event {ARROW}</a>
</div>

<script src="/assets/venues.js?v={ASSET_VER}"></script>
<script src="/assets/be.js?v={ASSET_VER}"></script>
</body>
</html>
'''


def write(page, title, desc, body, cta=True, sticky=True):
    html = head(title, desc, page) + header(page) + body
    if cta:
        html += CTA_BAND
    footer = FOOTER
    if not sticky:
        footer = re.sub(r'<div class="sticky-cta">.*?</div>\n\n', '', footer, flags=re.S)
    html += footer
    with open(os.path.join(OUT, page), 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'  {page:22s} {len(html):>7,} bytes')


# ============================================================ PAGES

FEATURES = '''    <div class="features">
      <div class="feature">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M3 13l2-5.5A2 2 0 017 6h10a2 2 0 011.9 1.5L21 13v5h-3v-2H6v2H3v-5z"/><circle cx="7.5" cy="15.5" r="1.2"/><circle cx="16.5" cy="15.5" r="1.2"/></svg>
        <h3>Affordable</h3>
        <p>Built around a car worth roughly $4,000 and an entry from $1,000 for the whole team.
          Split it six ways and it&rsquo;s cheaper than a weekend away.</p>
      </div>
      <div class="feature">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg>
        <h3>Real endurance racing</h3>
        <p>Six one-hour sessions. Teams, strategy, traffic, driver changes, refuelling and proper
          track time on real Australian circuits.</p>
      </div>
      <div class="feature">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9.5" r="2.3"/><path d="M3 19c0-3.3 2.7-5 6-5s6 1.7 6 5M16 14.5c2.8.2 5 1.8 5 4.5"/></svg>
        <h3>Anyone can get involved</h3>
        <p>Grassroots competitors, not professional race teams. Drivers from fourteen up, families,
          mates and workmates all welcome.</p>
      </div>
    </div>
'''

STEPS_HTML = '''    <div class="steps hiw-steps">
      <div class="step"><div class="step-n">1</div>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M3 13l2-5.5A2 2 0 017 6h10a2 2 0 011.9 1.5L21 13v5h-3v-2H6v2H3v-5z"/><circle cx="7.5" cy="15.5" r="1.2"/><circle cx="16.5" cy="15.5" r="1.2"/></svg>
        <h3>Find a car</h3><p>Cheap, reliable and legal. Marketplace bargains, auction finds and old family cars.</p></div>
      <div class="step"><div class="step-n">2</div>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9.5" r="2.3"/><path d="M3 19c0-3.3 2.7-5 6-5s6 1.7 6 5M16 14.5c2.8.2 5 1.8 5 4.5"/></svg>
        <h3>Build your team</h3><p>Three to six drivers. Grab your mates and get organised.</p></div>
      <div class="step"><div class="step-n">3</div>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 3l7 3v5.5c0 4.4-2.9 7.9-7 9.5-4.1-1.6-7-5.1-7-9.5V6l7-3z"/><path d="M9 12l2.2 2.2L15.5 10"/></svg>
        <h3>Meet the safety requirements</h3><p>Simple rules to keep everyone safe. Helmet, cotton, boots and a sound car.</p></div>
      <div class="step"><div class="step-n">4</div>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="3" y="5" width="18" height="12" rx="1"/><path d="M2 20h20"/></svg>
        <h3>Enter online</h3><p>Easy entry process. Entry from $1,000 for the whole team.</p></div>
      <div class="step"><div class="step-n">5</div>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M5 3v18"/><path d="M5 4h14v9H5z"/></svg>
        <h3>Go racing</h3><p>Real racing. Real fun. Six hours of track time in one day.</p></div>
    </div>
'''

HIW_ART = '''    <img class="hiw-art" src="/assets/how-it-works.jpg" width="1672" height="596"
      alt="From road car to race grid in five steps. One, find a car &mdash; cheap, reliable and legal. Two, build your team &mdash; grab your mates and get organised. Three, meet the safety requirements &mdash; simple rules to keep everyone safe. Four, enter online &mdash; easy entry process, $1,000 to enter. Five, go racing &mdash; real racing, real fun.">
'''


def build():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(os.path.join(OUT, 'assets', 'tracks'), exist_ok=True)
    print('Building Budget Enduro site\n')
    emit_venues_js()

    # ---------------------------------------------------------- HOME
    write('index.html',
          'Budget Enduro &mdash; Real cars. Real people. Real racing.',
          "Australia&rsquo;s grassroots endurance racing challenge. Grab your mates, find a cheap car and go racing.",
          f'''<div class="hero">
  <img class="hero-art" src="/assets/hero.jpg" width="1672" height="941"
       alt="Budget Enduro! Real cars. Real people. Real racing. Two budget endurance race cars running side by side on track.">
  <div class="hero-cta">
    <div class="container hero-cta-inner">
      <div class="hero-actions">
        <a class="btn btn-primary" href="enter">Enter an event {ARROW}</a>
        <a class="btn btn-ghost" href="how-it-works">How it works {ARROW}</a>
      </div>
      <div class="hero-badge">
        <b>Entry from $1,000</b>
        <span>The ultimate budget challenge</span>
      </div>
    </div>
  </div>
</div>

<section class="section section-light">
  <div class="container">
    <div class="intro-grid">
      <div>
        <h2>Proper racing.<span class="r">Without the silly budget.</span></h2>
        <div class="red-rule"></div>
      </div>
      <div>
        <p class="lead">Budget Enduro is Australia&rsquo;s endurance racing challenge for ordinary cars
          and ordinary people. Buy something cheap, get three mates together and race it on a proper
          circuit for a full day.</p>
        <p class="muted">You don&rsquo;t need a six-figure race car to have a proper race. Reliability
          beats speed, and the team that keeps its heap running usually beats the one that doesn&rsquo;t.</p>
      </div>
    </div>
{FEATURES}  </div>
</section>

<section class="section section-dark">
  <div class="container">
    <div class="sec-head">
      <div><h2>Next on the grid</h2><div class="red-rule"></div></div>
      <a class="btn btn-ghost btn-sm" href="events">View all events {ARROW}</a>
    </div>
    <div class="grid-events" data-events="3"></div>
  </div>
</section>

<section class="section section-white">
  <div class="container">
    <div class="sec-head">
      <div><h2>From road car to race grid</h2><div class="red-rule"></div></div>
      <a class="btn btn-dark btn-sm" href="how-it-works">Full guide {ARROW}</a>
    </div>
{HIW_ART}{STEPS_HTML}  </div>
</section>

<a class="statement" href="gallery">
  <img src="/assets/statement.jpg" width="1672" height="690"
       alt="Real cars. Real people. Real racing. View the gallery.">
</a>

<section class="section section-dark">
  <div class="container">
    <div class="sec-head"><div><h2>Why Budget Enduro</h2><div class="red-rule"></div></div></div>
    <div class="stats">
      <div class="stat"><b>From $1,000</b><span>Entry for the whole team</span></div>
      <div class="stat"><b>3&ndash;6 drivers</b><span>Share the car, share the cost</span></div>
      <div class="stat"><b>6 &times; 1 hour</b><span>Serious track time</span></div>
      <div class="stat"><b>~$4,000</b><span>Low-budget cars, high-budget fun</span></div>
      <div class="stat"><b>14+</b><span>Minimum driver age</span></div>
      <div class="stat"><b>5 circuits</b><span>Proper Australian race tracks</span></div>
    </div>
  </div>
</section>

<section class="section-sponsors">
  <img src="/assets/sponsors.jpg" width="2172" height="391"
       alt="Major sponsors: Raceworks &mdash; passion for performance, and Protex.">
  <div class="container">
    <div class="partner-slots">
      <div class="partner-slot">Supporting partner</div>
      <div class="partner-slot">Supporting partner</div>
      <div class="partner-slot">Supporting partner</div>
      <div class="partner-slot">Your business here<br>race@budgetenduro.com.au</div>
    </div>
  </div>
</section>
''')

    # ---------------------------------------------------------- EVENTS
    write('events.html',
          'Events &mdash; Budget Enduro',
          'Upcoming Budget Enduro rounds. Dates, venues, entry fees and entries.',
          page_head('Calendar', 'Next on the grid',
                    'Every remaining Budget Enduro round. Entries run through ArgusIQ &mdash; pick a '
                    'round, add your team and pay by card.') +
          f'''<section class="section section-light">
  <div class="container">
    <div class="grid-events" data-events="all"></div>

    <div class="past-note">
      <h2>Where we race</h2>
      <div class="red-rule"></div>
      <div class="venue-grid" id="venueGrid"></div>
      ''' + circuit_table() + '''
      <p class="muted" style="margin-top:18px">Past results for every round are in the
        <a href="results">Hall of Fame</a>.</p>
    </div>
  </div>
</section>
''')

    # ---------------------------------------------------------- ENTER
    write('enter.html',
          'Enter an event &mdash; Budget Enduro',
          'Enter your team in a Budget Enduro round. Entries and payments through ArgusIQ.',
          page_head('Entries', 'Get your team in',
                    'Pick a round, add your team and drivers, pay by card. Entries and payments run '
                    'on ArgusIQ &mdash; the same system that runs timing on the day, so your team '
                    'name goes straight onto the timing screen.') +
          '''<section class="section section-carbon">
  <div class="container">
    <div class="picker" id="picker" role="tablist" aria-label="Choose a round to enter"></div>
    <p class="muted" id="entryHeading" style="margin:0 0 18px;font-weight:600"></p>
    <div class="frame-shell">
      <iframe id="be-entry" title="Enter this event" loading="lazy"
        allow="payment; clipboard-write" src="about:blank"></iframe>
    </div>
    <p class="fallback">Form not loading?
      <a id="fallbackLink" href="https://www.argusiq.io/events">Open the entry form directly on
      ArgusIQ</a>. Trouble entering? Email
      <a href="mailto:race@budgetenduro.com.au">race@budgetenduro.com.au</a>.</p>
  </div>
</section>
''', cta=False, sticky=False)

    # ---------------------------------------------------------- HOW IT WORKS
    write('how-it-works.html',
          'How it works &mdash; Budget Enduro',
          'From road car to race grid. What you need, what it costs and what a race day looks like.',
          page_head('Getting started', 'From road car to race grid',
                    'Five steps between a Marketplace bargain and a full day of racing.') +
          f'''<section class="section section-white">
  <div class="container">
{HIW_ART}{STEPS_HTML}  </div>
</section>

<section class="section section-light">
  <div class="container">
    <div class="sec-head"><div><h2>Will my car pass?</h2><div class="red-rule"></div></div></div>
    <p style="max-width:58ch">Mass-produced road car, safe and trackworthy, road tyres, working brakes
      and steering, no major leaks, battery and seat secured. Registration isn&rsquo;t required. If
      you&rsquo;re eyeing something weird, send us photos <em>before</em> you spend the money.</p>

    <div class="two">
      <div class="col yes">
        <h3>Bring this</h3>
        <ul>
          <li>Auction bargains and Marketplace specials</li>
          <li>Old family cars and ex-taxis</li>
          <li>Forgotten paddock finds</li>
          <li>Weird engine swaps</li>
          <li>Creative Frankenstein builds</li>
          <li>Cars held together by determination and zip ties</li>
        </ul>
      </div>
      <div class="col no">
        <h3>Leave this home</h3>
        <ul>
          <li>Purpose-built race cars</li>
          <li>High-dollar competition vehicles</li>
          <li>Semi-slicks and R-spec tyres</li>
          <li>Anything unsafe</li>
          <li>Aggressive driving</li>
          <li>People taking it too seriously</li>
        </ul>
      </div>
    </div>
    <p class="note">Not sure? Email <a href="mailto:race@budgetenduro.com.au">race@budgetenduro.com.au</a>
      with photos and we&rsquo;ll tell you straight.</p>
  </div>
</section>

<section class="section section-white">
  <div class="container">
    <div class="sec-head"><div><h2>A typical race day</h2><div class="red-rule"></div></div></div>
    <div class="rules-grid">
      <div>
        <p class="muted">Six sessions, twenty-minute breaks. Refuel, swap drivers, fix whatever broke,
          eat a sausage.</p>
        <div class="scroller"><table>
          <thead><tr><th>Time</th><th>On the schedule</th></tr></thead>
          <tbody>
            <tr><td>07:00</td><td>Gates open, pit setup</td></tr>
            <tr><td>09:00</td><td>Session 1</td></tr>
            <tr><td>10:20</td><td>Session 2</td></tr>
            <tr><td>11:40</td><td>Session 3</td></tr>
            <tr><td>13:00</td><td>Session 4</td></tr>
            <tr><td>14:20</td><td>Session 5</td></tr>
            <tr><td>15:40</td><td>Session 6, chequered flag 16:40</td></tr>
          </tbody>
        </table></div>
      </div>
      <div>
        <p class="muted">Timetables vary between venues for noise limits, daylight and circuit
          operating requirements. Always work from the final schedule issued for your event.</p>
        <div class="cards" style="grid-template-columns:1fr">
          <div class="card">
            <h3>What to wear</h3>
            <p>Cotton or fire-retardant, neck to wrist to ankle. Fully enclosed leather footwear.
              Helmet to AS/NZS 1698, Snell or FIA. No shorts, no thongs, no polyester.</p>
          </div>
          <div class="card">
            <h3>Radios</h3>
            <p>Every car needs a working race radio that can hear Race Control. The frequency is
              issued before each event. No radio, no track.</p>
          </div>
          <div class="card">
            <h3>Refuelling</h3>
            <p>Session breaks only, car stationary, no work happening at the same time. Your team
              supplies a fire marshal with a 4.5kg dry powder extinguisher.</p>
          </div>
        </div>
      </div>
    </div>
    <p style="margin-top:34px"><a class="btn btn-dark" href="rules">Read the full regulations {ARROW}</a></p>
  </div>
</section>
''')

    # ---------------------------------------------------------- RULES
    write('rules.html',
          'Rules &amp; regulations &mdash; Budget Enduro',
          'The full Budget Enduro regulations. Eligibility, apparel, safety, minimum lap times, penalties.',
          page_head('Regulations', 'The rules',
                    'Twenty-one sections covering eligibility, apparel, vehicle safety, minimum lap '
                    'times, refuelling and penalties. New here? Start with '
                    '<a href="how-it-works" style="color:#fff">How it works</a>.') +
          RULES_BODY)

    # ---------------------------------------------------------- RESULTS
    write('results.html',
          'Results &amp; Hall of Fame &mdash; Budget Enduro',
          'Who did the most laps at every Budget Enduro round, by circuit.',
          page_head('Hall of Fame', 'Who did the most laps',
                    'There&rsquo;s no official winner and no trophy. There is a permanent public '
                    'record of exactly how many laps you managed. Make of that what you will.') +
          RESULTS_BODY)

    # ---------------------------------------------------------- GALLERY
    write('gallery.html',
          'Gallery &mdash; Budget Enduro',
          'Photos from Budget Enduro rounds. Cars, teams, pit lane and the paddock.',
          page_head('Photos', 'From the paddock',
                    'Cars leaning on it, driver changes, and teams fixing things that should not '
                    'have broken.') +
          '''<section class="section section-white">
  <div class="container">
    <div class="gallery" id="galleryGrid"></div>
    <p class="muted" style="margin-top:26px">Got photos from a round? Send them to
      <a href="mailto:race@budgetenduro.com.au">race@budgetenduro.com.au</a> and we&rsquo;ll put the
      good ones up.</p>
  </div>
</section>
''')

    # ---------------------------------------------------------- FAQ
    write('faq.html',
          'FAQ &mdash; Budget Enduro',
          'Common questions about entering Budget Enduro: cars, drivers, safety gear, licences and cost.',
          page_head('Questions', 'Common questions',
                    'Still stuck? Email race@budgetenduro.com.au and a human will answer.') +
          FAQ_BODY)

    # ---------------------------------------------------------- CONTACT
    write('contact.html',
          'Contact &mdash; Budget Enduro',
          'Get in touch with Budget Enduro. Email, phone and eligibility questions.',
          page_head('Get in touch', 'Contact us',
                    'Questions about a car, an entry or your team? Ask before you spend money.') +
          f'''<section class="section section-light">
  <div class="container">
    <div class="contact-grid">
      <div>
        <div class="contact-card">
          <h3>Talk to us</h3>
          <a class="big-link" href="mailto:race@budgetenduro.com.au">race@budgetenduro.com.au</a>
          <a class="big-link" href="tel:+61357626000">03 5762 6000</a>
          <p class="muted" style="margin:14px 0 0">Budget Enduro is run by Tampered Motorsport.</p>
        </div>
      </div>
      <div>
        <div class="contact-card">
          <h3>Is my car eligible?</h3>
          <p>Send photos and a few details before you buy or build anything borderline. We like weird
            and wonderful vehicles and we&rsquo;re happy to confirm eligibility up front so nobody
            wastes money.</p>
          <p style="margin:0"><a class="btn btn-dark btn-sm" href="how-it-works">Check the guide {ARROW}</a></p>
        </div>
        <div class="contact-card" style="margin-top:18px">
          <h3>Trouble with an entry</h3>
          <p>Entries and payments run on ArgusIQ. If a payment fails or you need to change drivers,
            email us and we&rsquo;ll sort it out.</p>
          <p style="margin:0"><a class="btn btn-primary btn-sm" href="enter">Enter an event {ARROW}</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
''')

    print('\nDone. Open site/index.html')


# ============================================================ LONG BODIES

RULES_BODY = '''<section class="section section-light">
  <div class="container">
    <nav class="toc" aria-label="Regulations contents">
      <h2>Contents</h2>
      <ol>
        <li><a href="#s1">Introduction</a></li>
        <li><a href="#s2">Nature of the event</a></li>
        <li><a href="#s3">Team requirements</a></li>
        <li><a href="#s4">Driver eligibility</a></li>
        <li><a href="#s5">Driver apparel</a></li>
        <li><a href="#s6">Vehicle eligibility</a></li>
        <li><a href="#s7">Vehicle value &amp; spirit</a></li>
        <li><a href="#s8">Frankenstein vehicles</a></li>
        <li><a href="#s9">Vehicle condition</a></li>
        <li><a href="#s10">Minimum safety requirements</a></li>
        <li><a href="#s11">Tyres</a></li>
        <li><a href="#s12">Driver communications</a></li>
        <li><a href="#s13">Event format</a></li>
        <li><a href="#s14">Driver participation</a></li>
        <li><a href="#s15">Refuelling</a></li>
        <li><a href="#s16">Mechanical repairs</a></li>
        <li><a href="#s17">Pit lane &amp; paddock speed</a></li>
        <li><a href="#s18">Minimum lap times</a></li>
        <li><a href="#s19">Awards</a></li>
        <li><a href="#s20">Penalties</a></li>
        <li><a href="#s21">Organiser discretion</a></li>
      </ol>
    </nav>

    <div class="reg">
      <h2 id="s1">1. Introduction</h2>
      <p>The Budget Enduro provides a fun, affordable and family-friendly motorsport activity in a
        safer environment than public roads. It is designed around inexpensive vehicles, teamwork,
        reliability and participation, and competitors are encouraged to involve family members,
        friends, work colleagues and fellow enthusiasts.</p>
      <p>The event is open to participants from fourteen (14) years of age and is intended as an
        enjoyable introduction to recreational motorsport.</p>

      <h2 id="s2">2. Nature of the event</h2>
      <p>The Budget Enduro is a recreational endurance challenge conducted under regularity-style
        conditions. It is not a race and is not intended to determine the fastest vehicle or driver.
        The objective is for teams to safely complete as many laps as possible while remaining within
        the regulations, the minimum lap time requirements and the spirit of the event.</p>
      <div class="pull">An endurance challenge, not a race. Reliability, consistency, teamwork and
        enjoyment ahead of outright speed.</div>
      <p>Results may be published, but the Budget Enduro does not recognise an official race winner.
        Awards and recognition may be presented for participation, team spirit, reliability,
        perseverance, ingenuity, sportsmanship and other achievements considered worthy by the
        organisers.</p>

      <h2 id="s3">3. Team requirements</h2>
      <p>Each vehicle must be entered by a team of a minimum of three (3) and a maximum of six (6)
        drivers. Teams without at least three nominated drivers may be refused participation.
        Additional drivers may not be added after the event has commenced without approval from Race
        Control.</p>

      <h2 id="s4">4. Driver eligibility</h2>
      <p>Drivers must hold the licence required by the event organiser and sanctioning body. The
        minimum age is fourteen (14) on the day of the event. All drivers must attend any compulsory
        driver briefing.</p>
      <p>Drivers are expected to behave safely and respectfully at all times. Dangerous driving,
        aggressive behaviour, deliberate contact, intimidation, bullying or conduct deemed unsafe by
        Race Control may result in penalties, exclusion from the event or suspension from future
        events. The decision of Race Control is final.</p>

      <h2 id="s5">5. Driver apparel</h2>
      <h3>Clothing</h3>
      <p>Drivers must wear clothing covering the body from neck to wrists and from waist to ankles
        while on track, manufactured from natural fibres or recognised fire-retardant materials.</p>
      <p>Acceptable: motorsport race suits, fire-retardant overalls, cotton drill overalls, cotton
        workwear, cotton long sleeve shirts and long pants.</p>
      <p>Not permitted: shorts, short sleeve shirts, singlets, clothing leaving skin exposed, nylon,
        polyester, acrylic, and other synthetics that may melt when exposed to heat or flame.</p>
      <div class="pull">If in doubt, wear cotton.</div>
      <h3>Footwear</h3>
      <p>Fully enclosed footwear is required. Acceptable: leather work boots, leather safety boots,
        motorsport footwear, leather enclosed shoes. Not permitted: thongs, sandals, open footwear,
        nylon or synthetic mesh running shoes, or any footwear deemed unsuitable by the organisers.</p>
      <h3>Helmets</h3>
      <p>All drivers must wear a helmet on track, complying with or exceeding AS/NZS 1698, Snell, FIA
        approved standards, or other standards approved by the organisers.</p>
      <p>Open-face and full-face helmets are both permitted. Open-face helmets must provide full
        coverage of the ears and sides of the head. Drivers of open-top vehicles must wear a full-face
        helmet.</p>
      <p>Not permitted: half helmets, skull caps, novelty helmets, bicycle helmets, construction
        helmets, or any helmet that does not adequately cover the ears and sides of the head. Any
        helmet considered damaged, modified or unsafe may be rejected.</p>
      <h3>Recommended</h3>
      <ul>
        <li>Fire-retardant overalls</li>
        <li>Gloves</li>
        <li>Balaclava</li>
        <li>Motorsport footwear</li>
        <li>HANS/FHR devices where harnesses are fitted</li>
      </ul>

      <h2 id="s6">6. Vehicle eligibility</h2>
      <p>Vehicles must be based on mass-produced, four-wheeled production vehicles originally
        manufactured for road use. Road registration is not required. Open-top vehicles are permitted
        provided suitable rollover protection is fitted and accepted by the organisers. The organisers
        reserve the right to accept or reject any vehicle entry.</p>

      <h2 id="s7">7. Vehicle value &amp; spirit of the event</h2>
      <p>As a guide, competitors should aim to keep the value of their vehicle to approximately $4,000
        or less. Value is assessed on the overall vehicle and does not include safety equipment,
        maintenance, repairs, reliability improvements, tyres or fuel.</p>
      <div class="pull">The ideal Budget Enduro car is a safe, reliable clunker rescued from
        Marketplace, Gumtree, auctions, paddocks, sheds or the back corner of a workshop.</div>
      <p>The intent is to encourage inexpensive everyday vehicles rather than high-value, specialist,
        prestige, exotic or purpose-built competition vehicles. Competitors with logbooked race cars
        are encouraged to compete in categories better suited to those vehicles.</p>
      <p>An Eligibility Committee appointed by the organisers will assess any vehicle that may fall
        outside the spirit of the event. Competitors considering the purchase or entry of a borderline
        vehicle are strongly encouraged to contact the organisers before spending money. The
        Eligibility Committee&rsquo;s decision is final.</p>

      <h2 id="s8">8. Frankenstein vehicles</h2>
      <p>Engine swaps, gearbox swaps, suspension upgrades, body modifications, custom fabrication and
        other creative engineering solutions are permitted and encouraged. There are very few
        prohibited modifications &mdash; if it is safe, affordable and within the spirit of the event,
        it will generally be considered.</p>
      <p>If you have built something weird, wonderful or difficult to categorise, we would love to see
        it. Vehicles that are excessively expensive or highly developed may be referred to the
        Eligibility Committee.</p>

      <h2 id="s9">9. Vehicle condition</h2>
      <p>Vehicles must be presented in a safe and trackworthy condition. The event is intentionally
        designed so competitors can buy an inexpensive vehicle and participate with minimal
        preparation, but it remains the entrant&rsquo;s responsibility to ensure the vehicle is
        suitable for a race circuit. Participation confirms the entrant believes the vehicle is fit
        for track use. Unsafe vehicles may be refused entry or removed at any time.</p>

      <h2 id="s10">10. Minimum vehicle safety requirements</h2>
      <h3>Brakes &amp; steering</h3>
      <ul><li>Effective brakes</li><li>Firm brake pedal</li><li>Functional steering system</li></ul>
      <h3>Fuel system</h3>
      <ul><li>Secure fuel system</li><li>No fuel leaks</li></ul>
      <h3>Fluid leaks</h3>
      <ul><li>No significant fuel, oil, coolant or brake fluid leaks</li></ul>
      <h3>Battery</h3>
      <ul><li>Securely mounted battery</li><li>Protected terminals where appropriate</li></ul>
      <h3>Seats &amp; seatbelts</h3>
      <ul><li>Secure driver&rsquo;s seat</li><li>Serviceable seatbelts</li></ul>
      <h3>Wheels &amp; tyres</h3>
      <ul><li>Secure wheels</li><li>All wheel nuts fitted</li><li>Tyres in safe condition</li></ul>
      <h3>Mirrors, body and lights</h3>
      <ul>
        <li>At least one functional rear vision mirror</li>
        <li>No loose items, secure bonnet and boot, no dangerous protrusions</li>
        <li>Operational brake lights</li>
        <li>Secure exhaust system complying with venue noise requirements</li>
      </ul>
      <h3>Fire extinguishers &amp; roll cages</h3>
      <ul>
        <li>Fire extinguishers strongly recommended, and must be securely mounted if fitted</li>
        <li>Roll cages are not required, but must be safe and secure if fitted</li>
      </ul>

      <h2 id="s11">11. Tyres</h2>
      <p>Tyres must be road legal and intended primarily for road use. Semi-slick, R-spec,
        competition, track-focused and specialist motorsport tyres are not permitted. Examples
        generally not permitted include the Toyo R888R, Yokohama A050 and A052, Nankang AR-1 and
        Michelin Pilot Sport Cup 2. This list is not exhaustive.</p>
      <p>All tyres must have at least 1.5mm tread depth across the tread surface, be free from exposed
        cords and free from significant cuts or sidewall damage, and comply with applicable
        roadworthiness requirements.</p>
      <p>Only one set of tyres may be used per event without penalty unless approved by Race Control.</p>

      <h2 id="s12">12. Driver communications</h2>
      <p>All vehicles must have a functioning race radio capable of receiving communications from Race
        Control. The approved frequency for each event will be advised by the organisers. Failure to
        maintain race radio communications may result in a vehicle being removed from the circuit.</p>

      <h2 id="s13">13. Event format</h2>
      <p>The event generally consists of multiple driving sessions separated by scheduled breaks.
        Session lengths, break durations and schedules are advised by the organisers for each event.
        The organisers reserve the right to alter the format for safety, operational or venue
        requirements.</p>

      <h2 id="s14">14. Driver participation</h2>
      <p>Driver participation requirements will be advised by the organisers. Teams are responsible
        for ensuring compliance.</p>

      <h2 id="s15">15. Refuelling</h2>
      <p>Refuelling may only occur during designated session breaks unless otherwise approved by Race
        Control. No maintenance may be carried out while refuelling is taking place.</p>
      <p>Teams must provide a fire marshal equipped with a minimum 4.5kg dry powder fire extinguisher.
        The vehicle must remain stationary throughout. Failure to comply may result in penalties or
        exclusion.</p>

      <h2 id="s16">16. Mechanical repairs</h2>
      <p>Repairs may be carried out during session breaks. Any person working underneath a vehicle
        must ensure it is adequately supported by approved safety stands. Unsafe repair practices may
        be prohibited. Pit crew must wear enclosed footwear and suitable clothing while working on
        vehicles.</p>

      <h2 id="s17">17. Pit lane &amp; paddock speed</h2>
      <p>Maximum speed in pit lane is 60 km/h unless otherwise advised by the organisers or venue
        management. Maximum speed in paddock, garage and competitor areas is walking pace. Unsafe
        driving in any non-track area may result in penalties or exclusion.</p>

      <h2 id="s18">18. Minimum lap times</h2>
      <p>Competitors who record laps faster than the prescribed minimum may have laps deleted, receive
        penalties, be directed to modify their driving behaviour, or be excluded. The purpose is to
        reinforce the endurance challenge nature of the event and discourage outright racing.</p>
      ''' + min_lap_table() + '''

      <h2 id="s19">19. Awards</h2>
      <p>The Budget Enduro does not recognise an official race winner and there is no winner&rsquo;s
        trophy. Awards may be presented for reliability, perseverance, team spirit, ingenuity,
        sportsmanship, vehicle presentation and other achievements recognised by the organisers, at
        the organisers&rsquo; discretion.</p>

      <h2 id="s20">20. Penalties</h2>
      <p>Penalties may be applied at the discretion of Race Control and event officials, and may
        include warnings, lap deletions, time penalties, sin bin penalties, exclusion from sessions or
        exclusion from the event. The more significant the breach, the greater the penalty may
        become.</p>

      <h2 id="s21">21. Organiser discretion</h2>
      <p>The organisers reserve the right to inspect any vehicle, apparel or safety equipment at any
        time. Any vehicle or competitor deemed unsafe or inconsistent with the spirit of the event may
        be refused entry, black flagged, removed from the circuit or excluded. The decision of the
        organisers, scrutineers, Race Control and the Eligibility Committee is final.</p>
    </div>
  </div>
</section>
'''

RESULTS_BODY = '''<section class="section section-dark">
  <div class="container">
    <div class="venues" role="tablist" aria-label="Choose a circuit">
      <button role="tab" aria-selected="true"  data-pane="sandown">Sandown</button>
      <button role="tab" aria-selected="false" data-pane="calder">Calder Park</button>
      <button role="tab" aria-selected="false" data-pane="broadford">Broadford</button>
      <button role="tab" aria-selected="false" data-pane="carnell">Carnell</button>
    </div>

    <div class="pane" id="pane-sandown">
      <div class="record"><b>213 laps</b><span>924 Motorsport &middot; Sandown &middot; 15 December 2024</span></div>
      <div class="scroller"><table>
        <thead><tr><th>Date</th><th>Most laps</th><th>Second</th><th>Third</th></tr></thead>
        <tbody>
          <tr><td>13/12/2025</td><td>924 Motorsport</td><td>Sh!t Heap Racing</td><td>Trutrack Racing</td></tr>
          <tr><td>06/09/2025</td><td>Sh!t Heap Racing</td><td>924 Motorsport</td><td>Drewballs Racing</td></tr>
          <tr><td>19/07/2025</td><td>The Cardashians</td><td>Industrial Environmental</td><td>Sh!t Heap Racing</td></tr>
          <tr><td>09/03/2025</td><td>Sh!t Heap Racing</td><td>Rag Tag Bunch of Blokes</td><td>Trutrack Racing</td></tr>
          <tr><td>15/12/2024</td><td>924 Motorsport</td><td>T-Swizzle</td><td>Team XR4ted</td></tr>
          <tr><td>16/11/2024</td><td>SORTHARE Suzuki Racing Team</td><td>CainCo Racing</td><td>Latino Heat</td></tr>
          <tr><td>07/07/2024</td><td>Team RHonda</td><td>Rag Tag Bunch Of Blokes</td><td>Team Ron</td></tr>
          <tr><td>14/04/2024</td><td>Team RHonda</td><td>SORTHARE Suzuki Racing Team</td><td>Summer Roll Racing</td></tr>
          <tr><td>28/01/2024</td><td>Rage Racer</td><td>Team Rhonald McNugget</td><td>WINGIT</td></tr>
          <tr><td>02/12/2023</td><td>Slow and Slower</td><td>924 Motorsport</td><td>Team Send It</td></tr>
          <tr><td>23/09/2023</td><td>Team Send It</td><td>0 Fast, 6 Furious</td><td>The Green Hornet</td></tr>
          <tr><td>22/07/2023</td><td>T-Swizzle</td><td>The Legend Continues</td><td>924 Motorsport</td></tr>
          <tr><td>04/06/2023</td><td>Team Ron</td><td>The Real POTC</td><td>Rag Tag Bunch Of Blokes</td></tr>
          <tr><td>23/04/2023</td><td>Rag Tag Bunch Of Blokes</td><td>Team Ron</td><td>T-Swizzle</td></tr>
          <tr><td>11/03/2023</td><td>T-Swizzle</td><td>Team Ron</td><td>The Legend Continues</td></tr>
          <tr><td>21/01/2023</td><td>Itchy Mickey Lancer</td><td>Team Rhonda</td><td>Rag Tag Bunch Of Blokes</td></tr>
          <tr><td>04/12/2022</td><td>Navjot Singh</td><td>3 Gen Racing</td><td>Red Terror</td></tr>
          <tr><td>30/10/2022</td><td>Vurgel Autosport</td><td>Wingkee</td><td>Pushing P</td></tr>
          <tr><td>27/08/2022</td><td>SORTHARE Suzuki Racing Team</td><td>3 Gen Racing</td><td>Wing Bros</td></tr>
          <tr><td>14/03/2022</td><td>RevSpeed Auto</td><td>Vurgel Autosport</td><td>Guff</td></tr>
          <tr><td>23/01/2022</td><td>Vurgel Autosport</td><td>The Distance</td><td>The Green Hornet</td></tr>
        </tbody>
      </table></div>
    </div>

    <div class="pane" id="pane-calder" hidden>
      <div class="record"><b>252 laps</b><span>Team Send It &middot; Calder Park &middot; 6 April 2025</span></div>
      <div class="scroller"><table>
        <thead><tr><th>Date</th><th>Most laps</th><th>Second</th><th>Third</th></tr></thead>
        <tbody>
          <tr><td>09/08/2026</td><td>Team RHonda</td><td>924 Motorsport</td><td>Sh!t Heap Racing</td></tr>
          <tr><td>05/07/2026</td><td>Sh!t Heap Racing</td><td>Team RHonda</td><td>Gooses Fast Flock</td></tr>
          <tr><td>26/04/2026</td><td>Team RHonda</td><td>924 Motorsport</td><td>Bavarian Missionary Workers</td></tr>
          <tr><td>09/06/2025</td><td>Team RHonda</td><td>Team Send It</td><td>Sh!t Heap Racing</td></tr>
          <tr><td>06/04/2025</td><td>Team Send It</td><td>CainCo Racing</td><td>Sh!t Heap Racing</td></tr>
        </tbody>
      </table></div>
    </div>

    <div class="pane" id="pane-broadford" hidden>
      <div class="record"><b>283 laps</b><span>Summer Roll Racing &middot; Broadford &middot; 9 June 2024</span></div>
      <div class="scroller"><table>
        <thead><tr><th>Date</th><th>Most laps</th><th>Second</th><th>Third</th></tr></thead>
        <tbody>
          <tr><td>09/06/2024</td><td>Summer Roll Racing</td><td>Trutrack Racing</td><td>924 Motorsport</td></tr>
        </tbody>
      </table></div>
    </div>

    <div class="pane" id="pane-carnell" hidden>
      <div class="record"><b>474 laps</b><span>Team Travis &middot; Carnell &middot; 22 October 2023</span></div>
      <div class="scroller"><table>
        <thead><tr><th>Date</th><th>Most laps</th><th>Second</th><th>Third</th></tr></thead>
        <tbody>
          <tr><td>18/02/2024</td><td>Lelax Racing</td><td>The Legend Continues</td><td>Herbie</td></tr>
          <tr><td>22/10/2023</td><td>Team Travis</td><td>Top Notch Racing</td><td>Da Boyz</td></tr>
        </tbody>
      </table></div>
    </div>

    <p class="muted" style="margin-top:30px">Live timing on race day runs at
      <a href="https://timing.argusiq.io" style="color:#fff">timing.argusiq.io</a>.</p>
  </div>
</section>
'''

FAQ_BODY = '''<section class="section section-white">
  <div class="container">
    <div class="faq">
      <details open><summary>What cars are eligible?</summary>
        <div class="answer">Mass-produced four-wheeled production cars originally built for the road,
          worth roughly $4,000 as a guide. Registration isn&rsquo;t required. Engine swaps, gearbox
          swaps and creative fabrication are all fine. Purpose-built race cars and high-dollar
          competition machinery are not.</div></details>
      <details><summary>How many drivers can enter?</summary>
        <div class="answer">Three drivers minimum, six maximum. Every driver is included in the team
          entry fee. Extra drivers can&rsquo;t be added once the event has started without Race
          Control&rsquo;s approval.</div></details>
      <details><summary>What safety equipment do I need?</summary>
        <div class="answer">A helmet to AS/NZS 1698, Snell or FIA standard, clothing covering neck to
          wrist to ankle in cotton or fire-retardant material, and fully enclosed leather footwear.
          Gloves, a balaclava and fire-retardant overalls are strongly recommended. Every car needs a
          working race radio.</div></details>
      <details><summary>Do I need a racing licence?</summary>
        <div class="answer">Drivers must hold whatever licence the event organiser and sanctioning body
          require for that round. The minimum age is fourteen on the day, and every driver must attend
          the compulsory briefing.</div></details>
      <details><summary>How much does it cost?</summary>
        <div class="answer">Entry starts from $1,000 for the whole team. Current rounds are $1,021,
          which works out around $170 each across six drivers. The exact fee is shown on each event
          when you go to <a href="enter">enter</a>.</div></details>
      <details><summary>Can beginners enter?</summary>
        <div class="answer">Yes &mdash; that&rsquo;s the whole point. Minimum lap times keep the pace
          sensible, and most teams are made up of people who&rsquo;ve never raced before. Reliability
          beats speed.</div></details>
      <details><summary>Where are events held?</summary>
        <div class="answer">Calder Park, Sandown Raceway and Broadford in Victoria, Mallala Motorsport
          Park in South Australia and Carnell Raceway in Queensland. See
          <a href="events">upcoming events</a>.</div></details>
      <details><summary>Is there a winner?</summary>
        <div class="answer">Officially, no. There&rsquo;s no race winner and no winner&rsquo;s trophy.
          Awards go to reliability, perseverance, team spirit, ingenuity and sportsmanship. The
          <a href="results">Hall of Fame</a> records who completed the most laps at each
          round.</div></details>
      <details><summary>Where do I find the regulations?</summary>
        <div class="answer">The full twenty-one section regulations cover apparel, vehicle
          eligibility, minimum lap times, refuelling, penalties and awards.
          <a href="rules">Read them here</a>.</div></details>
    </div>
  </div>
</section>
'''

if __name__ == '__main__':
    build()
